name: 'deploy snowflake integrations'

on:
  push:
    paths:
      - 'snowflake/infra/storage_integrations/**'

jobs:
  deploy-snowflake-integrations:
    runs-on: ubuntu-latest
    container: glasgowcannoners/new-tf-snow:latest
    environment: dev
    env:
      ENV: dev
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLENAME: SYSADMIN

    steps:
    - name: checkout-code
      uses: actions/checkout@v2

    - name: configure-AWS-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 900
        role-session-name: CI-deployment

    - name: deploy-integrations
      run: |
        cd snowflake/infra/storage_integrations
        terraform init
        terraform workspace new $ENV || terraform workspace select $ENV
        terraform plan
        terraform apply -input=false -auto-approve
